"""added created by and updated by with auditmixin

Revision ID: 4823bf330265
Revises: 5a4d5d470038
Create Date: 2024-11-21 18:32:06.109493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4823bf330265'
down_revision = '5a4d5d470038'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_symptoms', sa.Column('created_by', sa.String(length=100), nullable=False))
    op.add_column('business_symptoms', sa.Column('updated_by', sa.String(length=100), nullable=False))
    op.add_column('businesses', sa.Column('created_by', sa.String(length=100), nullable=False))
    op.add_column('businesses', sa.Column('updated_by', sa.String(length=100), nullable=False))
    op.add_column('symptoms', sa.Column('created_by', sa.String(length=100), nullable=False))
    op.add_column('symptoms', sa.Column('updated_by', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('symptoms', 'updated_by')
    op.drop_column('symptoms', 'created_by')
    op.drop_column('businesses', 'updated_by')
    op.drop_column('businesses', 'created_by')
    op.drop_column('business_symptoms', 'updated_by')
    op.drop_column('business_symptoms', 'created_by')
    # ### end Alembic commands ###
