"""added created at and updated at column in  table 

Revision ID: 5a4d5d470038
Revises: a16336582e7d
Create Date: 2024-11-21 18:06:56.882878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a4d5d470038'
down_revision = 'a16336582e7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_symptoms', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('business_symptoms', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('businesses', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('businesses', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('symptoms', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('symptoms', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('symptoms', 'updated_at')
    op.drop_column('symptoms', 'created_at')
    op.drop_column('businesses', 'updated_at')
    op.drop_column('businesses', 'created_at')
    op.drop_column('business_symptoms', 'updated_at')
    op.drop_column('business_symptoms', 'created_at')
    # ### end Alembic commands ###
