"""create businesses, sysmtoms, BusinessSymtoms tables

Revision ID: a16336582e7d
Revises: 
Create Date: 2024-11-21 17:19:18.631473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a16336582e7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('business_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('business_id')
    )
    op.create_table('symptoms',
    sa.Column('symptom_code', sa.String(length=50), nullable=False),
    sa.Column('symptom_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('symptom_code')
    )
    op.create_table('business_symptoms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('symptom_code', sa.String(length=50), nullable=False),
    sa.Column('symptom_diagnostic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.business_id'], ),
    sa.ForeignKeyConstraint(['symptom_code'], ['symptoms.symptom_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_symptoms')
    op.drop_table('symptoms')
    op.drop_table('businesses')
    # ### end Alembic commands ###
